# Generated by Django 4.0.3 on 2022-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YErrorMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('join_date', models.DateField()),
            ],
            options={
                'db_table': 'ymutation_error',
            },
        ),
        migrations.CreateModel(
            name='YMutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.PositiveIntegerField()),
                ('mutation_type', models.CharField(choices=[('SNP', 'SNP'), ('INDEL', 'INDEL')], max_length=5)),
                ('ancestral', models.CharField(max_length=100)),
                ('derived', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('ycc_haplogroup', models.TextField(blank=True, null=True)),
                ('isogg_haplogroup', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ymutation',
            },
        ),
        migrations.AddIndex(
            model_name='ymutations',
            index=models.Index(fields=['name'], name='ymutation_name_ded686_idx'),
        ),
        migrations.AddIndex(
            model_name='ymutations',
            index=models.Index(fields=['position'], name='ymutation_positio_fef5ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='ymutations',
            constraint=models.UniqueConstraint(fields=('name',), name='models_ymutations_unique_name'),
        ),
        migrations.AddIndex(
            model_name='yerrormutation',
            index=models.Index(fields=['name'], name='ymutation_e_name_bb292a_idx'),
        ),
        migrations.AddConstraint(
            model_name='yerrormutation',
            constraint=models.UniqueConstraint(fields=('name',), name='models_yerrormutation_unique_name'),
        ),
    ]
