# Generated by Django 4.2.16 on 2024-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ymutations',
            name='ymutation_name_ded686_idx',
        ),
        migrations.AddField(
            model_name='ymutations',
            name='ybrowse_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='ymutations',
            index=models.Index(fields=['join_date'], name='ymutation_join_da_186260_idx'),
        ),
    ]
